import { agentInfo, HUMAN } from "../agents.js";
import type { Report } from "../analyze.js";
import { pct, scopeLabel } from "./common.js";
import { esc } from "./svg.js";

/** A single self-contained HTML file: no network, no build step, safe to share. */
export function renderHtml(r: Report): string {
  const data = JSON.stringify({
    ...r,
    // Reports get shared: never embed the local checkout path.
    repo: { ...r.repo, path: undefined },
    palette: {
      human: HUMAN,
      bot: agentInfo("bot"),
    },
  }).replace(/</g, "\\u003c");
  const title = `${r.repo.name}: ${pct(r.totals.ai, r.totals.lines)} AI-written`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} · aiblame</title>
<meta name="description" content="${esc(`${pct(r.totals.ai, r.totals.lines)} ${scopeLabel(r)} of ${r.repo.name} was written by AI agents, according to aiblame.`)}">
<style>${CSS}</style>
</head>
<body>
<main>
  <header>
    <div class="brand"><span class="logo">aiblame</span> <span class="muted">git blame for the AI era</span></div>
    <h1 id="repo"></h1>
    <p class="muted" id="meta"></p>
  </header>
  <section class="hero">
    <div class="big" id="big"></div>
    <div class="sub" id="sub"></div>
    <div class="bar" id="bar"></div>
    <div class="legend" id="legend"></div>
  </section>
  <section class="cards" id="cards"></section>
  <section id="timeline-sec">
    <h2 id="timeline-title"></h2>
    <p class="muted" id="timeline-caption"></p>
    <div id="timeline"></div>
  </section>
  <section>
    <h2>The codebase, file by file</h2>
    <p class="muted">Area is lines of code. Colour is the agent that wrote most of the file; brighter means more AI. Hover for details.</p>
    <div id="treemap"></div>
  </section>
  <section class="grid2">
    <div><h2>Most AI-written files</h2><table id="files"></table></div>
    <div><h2>Directories</h2><table id="dirs"></table></div>
  </section>
  <section class="grid2">
    <div><h2>Languages</h2><table id="langs"></table></div>
    <div><h2>Evidence</h2><ul id="evidence" class="evidence"></ul></div>
  </section>
  <footer class="muted">
    <p><strong>How this works.</strong> Every line is traced with <code>git blame</code> to the commit that last touched it.
    A commit counts as AI-written when it carries an agent's fingerprint: a <code>Co-authored-by</code> trailer, a bot account,
    or an agent footer. Lines blamed on human commits can also be matched against local agent session transcripts.
    Unsigned AI code looks human to git, so treat every number here as a <em>lower bound</em>.</p>
    <p>Generated by <a href="https://www.npmjs.com/package/aiblame">aiblame</a> <span id="ver"></span>.</p>
  </footer>
</main>
<div id="tip" role="tooltip"></div>
<script type="application/json" id="data">${data}</script>
<script>${JS}</script>
</body>
</html>
`;
}

const CSS = `
:root{--bg:#ffffff;--panel:#f6f8fa;--fg:#1f2328;--muted:#656d76;--border:#d0d7de;--human:#d8dee4;--accent:#8250df;color-scheme:light}
@media (prefers-color-scheme:dark){:root{--bg:#0d1117;--panel:#161b22;--fg:#e6edf3;--muted:#8d96a0;--border:#30363d;--human:#262c36;--accent:#c084fc;color-scheme:dark}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif}
main{max-width:1080px;margin:0 auto;padding:32px 16px 64px}
h1{font-size:28px;margin:8px 0 0;word-break:break-word}
h2{font-size:17px;margin:0 0 4px}
section{margin-top:40px}
.muted{color:var(--muted)}
.brand{font-size:13px}
.logo{font-weight:700;color:var(--accent);letter-spacing:.02em}
.hero .big{font-size:clamp(56px,12vw,96px);font-weight:800;line-height:1;color:var(--accent);font-variant-numeric:tabular-nums}
.hero .sub{font-size:18px;margin:8px 0 20px}
.bar{display:flex;height:22px;border-radius:11px;overflow:hidden;background:var(--human)}
.bar span{height:100%}
.legend{display:flex;flex-wrap:wrap;gap:6px 18px;margin-top:12px;font-size:14px}
.legend i{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px;vertical-align:0}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}
.card{background:var(--panel);border:1px solid var(--border);border-radius:10px;padding:14px 16px}
.card b{display:block;font-size:24px;font-variant-numeric:tabular-nums}
.card span{color:var(--muted);font-size:13px}
#timeline svg{width:100%;height:auto;display:block;margin-top:12px}
#timeline text{fill:var(--muted);font-size:11px}
#treemap{position:relative;width:100%;height:clamp(320px,60vw,560px);margin-top:12px;border-radius:10px;overflow:hidden;background:var(--panel);border:1px solid var(--border)}
#treemap div{position:absolute;border:1px solid var(--bg);overflow:hidden;font-size:11px;line-height:1.2;padding:2px 3px;color:#fff;text-shadow:0 1px 2px rgba(0,0,0,.6);white-space:nowrap;text-overflow:ellipsis}
#treemap div.h{color:var(--muted);text-shadow:none}
.grid2{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,420px),1fr));gap:32px}
table{width:100%;border-collapse:collapse;font-size:13px;margin-top:8px;table-layout:fixed}
td{padding:5px 6px;border-bottom:1px solid var(--border);vertical-align:middle}
td.p{width:62px;text-align:right;font-variant-numeric:tabular-nums;font-weight:600}
td.n{width:76px;text-align:right;color:var(--muted);font-variant-numeric:tabular-nums}
td.path{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;direction:rtl;text-align:left}
td.meter{width:90px}
.meter-bar{height:8px;border-radius:4px;background:var(--human);overflow:hidden;display:flex}
.evidence{padding-left:18px;margin:8px 0}
.evidence li{margin:4px 0}
footer{margin-top:48px;font-size:13px;border-top:1px solid var(--border);padding-top:16px}
code{font-size:12px;background:var(--panel);padding:1px 4px;border-radius:4px}
a{color:var(--accent)}
#tip{position:fixed;pointer-events:none;background:var(--panel);color:var(--fg);border:1px solid var(--border);border-radius:8px;padding:8px 10px;font-size:12px;box-shadow:0 4px 16px rgba(0,0,0,.25);display:none;max-width:360px;z-index:10}
#tip b{word-break:break-all}
`;

// Browser-side code. Plain ES2017, no template literals (this file is itself one).
const JS = String.raw`
(function () {
  var R = JSON.parse(document.getElementById("data").textContent);
  var AG = {};
  R.agents.forEach(function (a) { AG[a.id] = a; });
  AG.human = R.palette.human; AG.bot = R.palette.bot;
  function info(id) { return AG[id] || { id: id, name: id, color: "#C084FC" }; }
  function isAI(id) { return id !== "human" && id !== "bot"; }
  function num(n) { return n.toLocaleString("en-US"); }
  function pct(a, b) {
    if (!b || !a) return "0%";
    var p = a / b * 100;
    if (p < 0.1) return "<0.1%";
    if (p > 99.9 && a < b) return ">99.9%";
    return (p >= 10 ? p.toFixed(1).replace(/\.0$/, "") : p.toFixed(1)) + "%";
  }
  function el(tag, attrs, text) {
    var e = document.createElement(tag);
    for (var k in attrs || {}) e.setAttribute(k, attrs[k]);
    if (text != null) e.textContent = text;
    return e;
  }
  function $(id) { return document.getElementById(id); }
  var T = R.totals;
  var order = R.agents.filter(function (a) { return a.lines > 0; }).map(function (a) { return a.id; });
  if (T.bot) order.push("bot");
  order.push("human");

  $("repo").textContent = R.repo.name;
  $("meta").textContent = [R.repo.branch, R.repo.sha.slice(0, 7), num(T.files) + " files",
    num(T.lines) + (R.mode === "history" ? " lines added" : " lines"), "generated " + R.generatedAt.slice(0, 10)]
    .filter(Boolean).join(" · ");
  $("ver").textContent = "v" + R.tool.version;
  $("big").textContent = (R.sample ? "~" : "") + pct(T.ai, T.lines);
  $("sub").textContent = (R.mode === "history"
    ? (R.since ? "of lines added since " + R.since : "of all lines ever added")
    : "of the current code") + (R.codeOnly ? " (docs, config and data excluded)" : "") + " was written by AI agents" +
    (R.sample ? " (±" + (R.sample.margin * 100).toFixed(1) + "%, estimated from " + num(R.sample.files) + " random files of " + num(R.sample.of) + ")" : "");
  $("timeline-title").textContent = R.mode === "history" ? "AI share of lines added, month by month" : "Current code, by the month it was written";
  $("timeline-caption").textContent = R.mode === "history"
    ? "Each column is 100% of the lines added that month, split by who wrote them."
    : "Each column is 100% of the surviving lines first written that month, split by who wrote them.";
  document.title = R.repo.name + ": " + pct(T.ai, T.lines) + " AI-written · aiblame";

  order.forEach(function (id) {
    var lines = id === "human" ? T.human : id === "bot" ? T.bot : info(id).lines;
    if (!lines) return;
    var s = el("span", { title: info(id).name + ": " + pct(lines, T.lines) });
    s.style.width = (lines / T.lines * 100) + "%";
    s.style.background = id === "human" ? "var(--human)" : info(id).color;
    $("bar").appendChild(s);
    var l = el("span");
    var dot = el("i"); dot.style.background = id === "human" ? "var(--human)" : info(id).color;
    l.appendChild(dot);
    l.appendChild(document.createTextNode(info(id).name + " "));
    l.appendChild(el("span", { class: "muted" }, pct(lines, T.lines)));
    $("legend").appendChild(l);
  });

  var C = R.commits;
  var cards = [
    [num(T.ai), "AI-written lines"],
    [num(C.ai), "AI-signed commits of " + num(C.total)],
    [String(R.agents.filter(function (a) { return a.lines > 0 || a.commits > 0; }).length), "agents detected"],
    [C.firstAi ? C.firstAi.date.slice(0, 10) : "never", C.firstAi ? "first AI commit (" + info(C.firstAi.agent).name + ")" : "first AI commit"],
    [C.humanAuthors ? pct(C.aiAssistedAuthors, C.humanAuthors) : "n/a", "of human contributors ship AI commits"]
  ];
  cards.forEach(function (c) {
    var d = el("div", { class: "card" });
    d.appendChild(el("b", null, c[0])); d.appendChild(el("span", null, c[1]));
    $("cards").appendChild(d);
  });

  var tip = $("tip");
  function showTip(e, html) {
    tip.innerHTML = html; tip.style.display = "block";
    var x = e.clientX + 14, y = e.clientY + 14;
    var r = tip.getBoundingClientRect();
    if (x + r.width > innerWidth - 8) x = e.clientX - r.width - 14;
    if (y + r.height > innerHeight - 8) y = e.clientY - r.height - 14;
    tip.style.left = x + "px"; tip.style.top = y + "px";
  }
  function hideTip() { tip.style.display = "none"; }
  function escH(s) { return String(s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }
  function breakdown(by, total) {
    return Object.keys(by).sort(function (a, b) { return by[b] - by[a]; }).map(function (id) {
      return '<div><span style="color:' + (id === "human" ? "var(--muted)" : info(id).color) + '">&#9632;</span> ' +
        escH(info(id).name) + " " + pct(by[id], total) + " <span class=muted>(" + num(by[id]) + ")</span></div>";
    }).join("");
  }

  // --- Timeline: 100% stacked columns -------------------------------------
  var months = R.timeline.filter(function (m) { return m.added > 0; });
  if (months.length < 2) { $("timeline-sec").style.display = "none"; }
  else {
    var ns = "http://www.w3.org/2000/svg";
    var MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    var W = 1000, H = 220, pad = 22, n = months.length, cw = W / n, gap = Math.min(3, cw * 0.2);
    var svg = document.createElementNS(ns, "svg");
    svg.setAttribute("viewBox", "0 0 " + W + " " + (H + pad));
    var tlOrder = order.slice();
    months.forEach(function (m) {
      Object.keys(m.by).forEach(function (id) { if (tlOrder.indexOf(id) < 0) tlOrder.splice(tlOrder.length - 1, 0, id); });
    });
    months.forEach(function (m, i) {
      var y = H;
      var g = document.createElementNS(ns, "g");
      tlOrder.forEach(function (id) {
        var v = m.by[id] || 0; if (!v) return;
        var h = v / m.added * H;
        var rect = document.createElementNS(ns, "rect");
        rect.setAttribute("x", i * cw + gap / 2); rect.setAttribute("width", Math.max(1, cw - gap));
        rect.setAttribute("y", y - h); rect.setAttribute("height", h);
        rect.setAttribute("fill", id === "human" ? "var(--human)" : info(id).color);
        g.appendChild(rect); y -= h;
      });
      var hit = document.createElementNS(ns, "rect");
      hit.setAttribute("x", i * cw); hit.setAttribute("width", cw); hit.setAttribute("y", 0); hit.setAttribute("height", H);
      hit.setAttribute("fill", "transparent");
      hit.addEventListener("mousemove", function (e) {
        showTip(e, "<b>" + m.month + "</b><div>" + num(m.added) + " lines added, " + pct(m.ai, m.added) + " by AI</div>" + breakdown(m.by, m.added));
      });
      hit.addEventListener("mouseleave", hideTip);
      g.appendChild(hit);
      svg.appendChild(g);
      var year = m.month.slice(0, 4);
      var newYear = i === 0 || months[i - 1].month.slice(0, 4) !== year;
      var label = n <= 18
        ? MONTHS[+m.month.slice(5, 7) - 1] + (newYear ? " " + year : "")
        : (newYear ? year : "");
      if (label) {
        var t = document.createElementNS(ns, "text");
        t.setAttribute("x", i * cw + 2); t.setAttribute("y", H + 16); t.textContent = label;
        svg.appendChild(t);
      }
    });
    $("timeline").appendChild(svg);
  }

  // --- Treemap: directories, then files ------------------------------------
  function squarify(nodes, x, y, w, h) {
    var out = [];
    var total = nodes.reduce(function (s, n) { return s + n.value; }, 0);
    if (!total || w <= 0 || h <= 0) return out;
    var scale = w * h / total;
    var items = nodes.map(function (n) { return { n: n, a: n.value * scale }; }).sort(function (a, b) { return b.a - a.a; });
    var row = [];
    function sum(r) { return r.reduce(function (s, i) { return s + i.a; }, 0); }
    function worst(r, side) {
      if (!r.length) return Infinity;
      var s = sum(r), mx = 0, mn = Infinity;
      r.forEach(function (i) { mx = Math.max(mx, i.a); mn = Math.min(mn, i.a); });
      return Math.max(side * side * mx / (s * s), s * s / (side * side * mn));
    }
    function flush() {
      if (!row.length) return;
      var s = sum(row);
      if (w >= h) {
        var cw = s / h, cy = y;
        row.forEach(function (i) { var ih = i.a / cw; out.push({ n: i.n, x: x, y: cy, w: cw, h: ih }); cy += ih; });
        x += cw; w -= cw;
      } else {
        var rh = s / w, cx = x;
        row.forEach(function (i) { var iw = i.a / rh; out.push({ n: i.n, x: cx, y: y, w: iw, h: rh }); cx += iw; });
        y += rh; h -= rh;
      }
      row = [];
    }
    while (items.length) {
      var side = Math.min(w, h);
      if (!row.length || worst(row.concat([items[0]]), side) <= worst(row, side)) row.push(items.shift());
      else flush();
    }
    flush();
    return out;
  }
  function aiOf(by) { var s = 0; for (var k in by) if (isAI(k)) s += by[k]; return s; }
  function dominant(by) { var best = null, n = 0; for (var k in by) if (isAI(k) && by[k] > n) { best = k; n = by[k]; } return best; }
  var box = $("treemap");
  function drawTreemap() {
    box.innerHTML = "";
    var W = box.clientWidth, H = box.clientHeight;
    var files = R.files.slice().sort(function (a, b) { return b.lines - a.lines; }).slice(0, 2500);
    var dirs = {};
    files.forEach(function (f) {
      var d = f.path.indexOf("/") > 0 ? f.path.slice(0, f.path.indexOf("/")) : "./";
      (dirs[d] = dirs[d] || { name: d, value: 0, files: [] }).files.push({ value: f.lines, f: f });
      dirs[d].value += f.lines;
    });
    squarify(Object.keys(dirs).map(function (k) { return dirs[k]; }), 0, 0, W, H).forEach(function (d) {
      var headH = d.h > 60 && d.w > 60 ? 16 : 0;
      if (headH) {
        var hd = el("div", { class: "h" }, d.n.name + (d.n.name === "./" ? "" : "/"));
        hd.style.cssText = "left:" + d.x + "px;top:" + d.y + "px;width:" + d.w + "px;height:" + headH + "px;border:0";
        box.appendChild(hd);
      }
      squarify(d.n.files, d.x, d.y + headH, d.w, d.h - headH).forEach(function (c) {
        var f = c.n.f, ai = aiOf(f.by), dom = dominant(f.by);
        var div = el("div");
        var s = ai / f.lines;
        div.style.cssText = "left:" + c.x + "px;top:" + c.y + "px;width:" + c.w + "px;height:" + c.h + "px";
        div.style.background = dom ? "color-mix(in srgb, " + info(dom).color + " " + Math.round(Math.sqrt(s) * 100) + "%, var(--human))" : "var(--human)";
        if (!dom) div.className = "h";
        if (c.w > 50 && c.h > 16) div.textContent = f.path.slice(f.path.lastIndexOf("/") + 1);
        div.addEventListener("mousemove", function (e) {
          showTip(e, "<b>" + escH(f.path) + "</b><div>" + num(f.lines) + " lines, " + pct(ai, f.lines) + " AI</div>" + breakdown(f.by, f.lines));
        });
        div.addEventListener("mouseleave", hideTip);
        box.appendChild(div);
      });
    });
  }
  drawTreemap();
  var rt; addEventListener("resize", function () { clearTimeout(rt); rt = setTimeout(drawTreemap, 150); });

  // --- Tables ----------------------------------------------------------------
  function meter(by, total) {
    var m = el("div", { class: "meter-bar" });
    order.forEach(function (id) {
      if (id === "human" || !by[id]) return;
      var s = el("span"); s.style.width = (by[id] / total * 100) + "%"; s.style.background = info(id).color; m.appendChild(s);
    });
    return m;
  }
  function row(table, p, path, lines, by, total) {
    var tr = el("tr");
    tr.appendChild(el("td", { class: "p" }, p));
    var td = el("td", { class: "meter" }); td.appendChild(meter(by, total)); tr.appendChild(td);
    var pt = el("td", { class: "path", title: path }); pt.appendChild(el("bdi", null, path)); tr.appendChild(pt);
    tr.appendChild(el("td", { class: "n" }, num(lines)));
    tr.addEventListener("mousemove", function (e) { showTip(e, "<b>" + escH(path) + "</b>" + breakdown(by, total)); });
    tr.addEventListener("mouseleave", hideTip);
    table.appendChild(tr);
  }
  var withAi = R.files.map(function (f) { return { f: f, ai: aiOf(f.by) }; }).filter(function (x) { return x.ai > 0; });
  withAi.sort(function (a, b) {
    var big = (b.f.lines >= 20) - (a.f.lines >= 20);
    return big || b.ai / b.f.lines - a.ai / a.f.lines || b.ai - a.ai;
  });
  withAi.slice(0, 15).forEach(function (x) { row($("files"), pct(x.ai, x.f.lines), x.f.path, x.f.lines, x.f.by, x.f.lines); });
  if (!withAi.length) $("files").appendChild(el("tr")).appendChild(el("td", null, "No AI-written files found."));

  var dirStats = {};
  R.files.forEach(function (f) {
    var parts = f.path.split("/");
    var d = parts.length > 1 ? parts.slice(0, Math.min(2, parts.length - 1)).join("/") + "/" : "./";
    var s = dirStats[d] = dirStats[d] || { path: d, lines: 0, ai: 0, by: {} };
    s.lines += f.lines;
    for (var k in f.by) { s.by[k] = (s.by[k] || 0) + f.by[k]; if (isAI(k)) s.ai += f.by[k]; }
  });
  Object.keys(dirStats).map(function (k) { return dirStats[k]; })
    .sort(function (a, b) { return b.ai - a.ai || b.lines - a.lines; }).slice(0, 15)
    .forEach(function (d) { row($("dirs"), pct(d.ai, d.lines), d.path, d.lines, d.by, d.lines); });

  R.languages.slice(0, 12).forEach(function (l) {
    var by = {}; by.human = l.lines - l.ai;
    var tr = el("tr");
    tr.appendChild(el("td", { class: "p" }, pct(l.ai, l.lines)));
    var td = el("td", { class: "meter" });
    var m = el("div", { class: "meter-bar" }); var s = el("span");
    s.style.width = (l.ai / l.lines * 100) + "%"; s.style.background = "var(--accent)"; m.appendChild(s); td.appendChild(m);
    tr.appendChild(td);
    tr.appendChild(el("td", null, l.name));
    tr.appendChild(el("td", { class: "n" }, num(l.lines)));
    $("langs").appendChild(tr);
  });

  var ev = $("evidence");
  function li(t) { ev.appendChild(el("li", null, t)); }
  li(num(R.evidence.signedCommits) + " of " + num(C.total) + " commits carry an AI signature (co-author trailer, bot account or agent footer).");
  if (R.evidence.transcriptLines) {
    li(num(R.evidence.transcriptLines) + " more lines were matched in local agent transcripts (" +
      R.evidence.transcripts.map(function (t) { return info(t.agent).name + ": " + t.files + " sessions"; }).join(", ") + ").");
  }
  function plural(n, w) { return num(n) + " " + w + (n === 1 ? "" : "s"); }
  R.agents.filter(function (a) { return a.commits > 0 || a.lines > 0; }).forEach(function (a) {
    var what = R.mode === "history" ? " lines added across " : " surviving lines in ";
    li(a.name + ": " + plural(a.commits, "commit") + ", " +
      (a.lines ? num(a.lines) + what + plural(a.files, "file") : "none of its lines survive") +
      (a.transcriptLines ? " (" + num(a.transcriptLines) + " via local transcripts)" : "") + ".");
  });
  if (C.latestAi) li("Most recent AI commit: " + C.latestAi.sha.slice(0, 7) + " on " + C.latestAi.date.slice(0, 10) + " (" + info(C.latestAi.agent).name + ").");
  if (R.repo.shallow) li("Warning: shallow clone. Lines older than the clone boundary are blamed on a single commit.");
})();
`;

